function isBot(){let userAgent=navigator.userAgent.toLowerCase();let botPatterns=[/bot/,/crawl/,/spider/,/slurp/,/curl/,/wget/,/python/,/scrapy/,/chrome-lighthouse/];let isWebDriver=navigator.webdriver;if(isWebDriver)return!0;return botPatterns.some(pattern=>pattern.test(userAgent))}
function isPC(){const userAgent=navigator.userAgent.toLowerCase();const isMobile=/iphone|ipad|android|mobile|blackberry|iemobile|opera mini/.test(userAgent);return!isMobile}
document.addEventListener("DOMContentLoaded",function(){const menuItems=document.querySelectorAll(".head-more-menu");menuItems.forEach(item=>{const submenu=item.querySelector(".head-more");const link=item.querySelector(".this-get");item.addEventListener("mouseenter",()=>{submenu.style.display="block";link.classList.add("active")});item.addEventListener("mouseleave",()=>{submenu.style.display="none";link.classList.remove("active")})})});document.addEventListener("DOMContentLoaded",function(){const menuButton=document.querySelector(".gen-left-list-mobile");const menu=document.querySelector(".drawer-list");const overlay=document.querySelector(".drawer-list-bg");menuButton.addEventListener("click",function(){menu.classList.add("v-show");menu.classList.remove("v-hidden");overlay.classList.add("v-show");overlay.classList.remove("v-hidden")});overlay.addEventListener("click",function(){menu.classList.add("v-hidden");menu.classList.remove("v-show");overlay.classList.add("v-hidden");overlay.classList.remove("v-show")})});document.addEventListener("DOMContentLoaded",function(){const lazyImages=document.querySelectorAll("img.lazy");const imgObserver=new IntersectionObserver((entries,observer)=>{entries.forEach(entry=>{if(entry.isIntersecting){const img=entry.target;let imgSrc=img.dataset.src;if(!imgSrc.includes('&w=')){if(!isPC()){imgSrc+='&w=270'}else{imgSrc+='&w=320'}}
imgSrc='https://images.weserv.nl/?url='+imgSrc+'&output=webp';const newImg=new Image();newImg.onload=function(){img.src=imgSrc};newImg.src=imgSrc;observer.unobserve(img)}})});lazyImages.forEach(img=>imgObserver.observe(img))});document.addEventListener("DOMContentLoaded",function(){let w=1080;if(!isPC()){w=720}
const lazyBgElements=document.querySelectorAll(".lazy-bg");const bgObserver=new IntersectionObserver((entries,observer)=>{entries.forEach(entry=>{if(entry.isIntersecting){const bgElement=entry.target;const bgUrl=bgElement.dataset.bg;if(bgUrl){bgElement.style.backgroundImage=`url('https://images.weserv.nl/?url=${bgUrl}&w=${w}&output=webp')`;bgElement.classList.remove("lazy-bg")}
observer.unobserve(bgElement)}})});lazyBgElements.forEach(el=>bgObserver.observe(el))});function toggleChildren(contentId,iconId){const content=document.getElementById(contentId);const icon=document.getElementById(iconId);if(content.classList.contains('ds-none')){content.classList.remove('ds-none');icon.innerHTML=''}else{content.classList.add('ds-none');icon.innerHTML=''}}
window.addEventListener('scroll',function(){const nav=document.getElementById('nav');if(window.scrollY>0){nav.classList.add('head-b');nav.style.position='fixed'}else{nav.classList.remove('head-b');nav.style.position=''}});function renderHistory(){let history=(JSON.parse(localStorage.getItem('searchHistory'))||[]).slice(0,5);if(history.length===0)return $('#result').html('');let html=`
        <span>
            <div class="rowsearch">
                <div class="column rights" style="margin-left: 10px;">
                    <p class="hide">Lịch sử tìm kiếm</p>
                </div>
                <div class="column lefts">
                    <i class="fa r6 ds-shanchu2" style="font-size: 16px; cursor: pointer;" onclick="clearHistory()"></i>
                </div>
            </div>
        </span>
    `;history.forEach(item=>{html+=`
            <div class="rowsearch item">
                <a href="/?search=${encodeURIComponent(item)}" style="flex: 1; margin-left: 10px;">
                    <div class="column rights">
                        <p class="hide">${item}</p>
                    </div>
                </a>
                <div class="column lefts">
                    <i class="fa r6 ds-guanbi2" style="font-size: 12px; cursor: pointer;"
                       onclick="event.stopPropagation(); event.preventDefault(); removeHistory('${item}')"></i>
                </div>
            </div>
        `});$('#result').html(html)}
function addSearchTerm(term){let history=JSON.parse(localStorage.getItem('searchHistory'))||[];term=term.trim();if(!term)return;history=history.filter(t=>t!==term);history.unshift(term);if(history.length>10)history.pop();localStorage.setItem('searchHistory',JSON.stringify(history))}
function removeHistory(term){let history=JSON.parse(localStorage.getItem('searchHistory'))||[];history=history.filter(item=>item!==term);localStorage.setItem('searchHistory',JSON.stringify(history));renderHistory()}
function clearHistory(){localStorage.removeItem('searchHistory');renderHistory()}
function getSearchParam(){const urlParams=new URLSearchParams(window.location.search);return urlParams.get('search')}
$(document).ready(function(){$(".preloading").delay(750).fadeOut();const searchTerm=getSearchParam();if(searchTerm){addSearchTerm(searchTerm)}
$('#search input').on('click',function(e){e.stopPropagation();renderHistory()});$("body").on("click",function(){$("#result").html('')});$(".filter-btn, .btn-close-filter").on("click",function(e){e.preventDefault();let filterForm=$('.filter-form');let filterBtn=$('.filter-btn');if(filterForm.hasClass('v-hidden')){filterBtn.html('<i class="fa r6 ease"></i>Bộ lọc');filterForm.removeClass('v-hidden')}else{filterBtn.html('<i class="fa r6 ease"></i>Bộ lọc');filterForm.addClass('v-hidden')}});$(".filter-item").on("click",function(e){e.preventDefault();let type=$(this).data('type');let id=$(this).data('id');let container=$('#'+type);if(type==='country'||type==='category'||type==='year'||type==='language'){if(id===""){container.find(".filter-item").removeClass("active");container.find('.filter-item[data-id=""]').addClass("active")}else if(id==="other"){container.find(".filter-item").removeClass("active");container.find('.filter-item[data-id="other"]').addClass("active")}else{container.find('.filter-item[data-id=""]').removeClass("active");$(this).toggleClass("active");if(container.find(".filter-item.active").length===0){container.find('.filter-item[data-id=""]').addClass("active")}}}else{$('#'+type+" .filter-item").removeClass("active");$(this).addClass("active")}});$(".btn-filter").on("click",function(e){e.preventDefault();var filterType=$('#type .filter-item.active').data('id');var filterCategory=$('#category .filter-item.active').map(function(){return $(this).data('id')}).get();var filterCountry=$('#country .filter-item.active').map(function(){return $(this).data('id')}).get();var filterYear=$('#year .filter-item.active').map(function(){return $(this).data('id')}).get();var filterLanguage=$('#language .filter-item.active').map(function(){return $(this).data('id')}).get();var filterSort=$('#sort .filter-item.active').data('id');var url=new URL(window.location.href);var baseUrl=url.origin;url.searchParams.set('filter[type]',filterType);url.searchParams.set('filter[category]',filterCategory.join(','));url.searchParams.set('filter[country]',filterCountry.join(','));url.searchParams.set('filter[year]',filterYear.join(','));url.searchParams.set('filter[language]',filterLanguage.join(','));url.searchParams.set('filter[sort]',filterSort);window.location.href=baseUrl+url.search})})