document.addEventListener('DOMContentLoaded',function(){let d=document,s=d.createElement('script')
s.src='https://https-phim1080-store.disqus.com/embed.js'
s.setAttribute('data-timestamp',+new Date());(d.head||d.body).appendChild(s)
requestAnimationFrame(()=>{new Swiper('.actor-roll',{slidesPerView:4,slidesPerGroup:4,grid:{rows:2,fill:'row',},spaceBetween:8,breakpoints:{1692:{slidesPerView:11,slidesPerGroup:11,spaceBetween:30},1330:{slidesPerView:9,slidesPerGroup:9,spaceBetween:30},993:{slidesPerView:7,slidesPerGroup:7,spaceBetween:30},560:{slidesPerView:6,slidesPerGroup:6,spaceBetween:15},},a11y:{enabled:!1},})})
document.querySelectorAll('.select-list').forEach((el)=>{el.addEventListener('click',function(e){e.preventDefault()
const serverId=this.getAttribute('data-id')
document.querySelectorAll('.list-content').forEach((c)=>c.classList.add('none'))
const target=document.getElementById('div-'+serverId)
if(target)target.classList.remove('none')
document.querySelectorAll('.select-list').forEach((sl)=>sl.classList.remove('active'))
this.classList.add('active')})})
document.querySelectorAll('.vod-playerUrl').forEach((el)=>{el.addEventListener('click',function(e){e.preventDefault()
const serverId=this.getAttribute('data-id')
document.querySelectorAll('.server-content').forEach((c)=>c.classList.add('none'))
const target=document.getElementById('episode-'+serverId)
if(target)target.classList.remove('none')
document.querySelectorAll('.vod-playerUrl').forEach((sl)=>sl.classList.remove('active'))
this.classList.add('active')})})
const desc=document.querySelector('.banner-content__desc')
const button=document.querySelector('.intl-album-more-btn')
if(desc&&button){if(desc.scrollHeight<=desc.clientHeight){button.style.display='none'}else{button.style.display='flex'}
button.addEventListener('click',function(){if(desc.classList.contains('line-clamp-3')){desc.classList.remove('line-clamp-3')
this.innerHTML='Ẩn bớt<i class="fa r6 ease"></i>'}else{desc.classList.add('line-clamp-3')
this.innerHTML='Hiển thị thêm<i class="fa r6 ease"></i>'}})}
document.querySelector('#share-btn')?.addEventListener('click',function(e){e.preventDefault();let url=window.location.href;let title=document.title;if(navigator.share){navigator.share({title:title,url:url})}else{let shareUrl=`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;window.open(shareUrl,'_blank','width=600,height=400')}});document.querySelector('#collect-btn')?.addEventListener('click',function(e){e.preventDefault()
let collections=JSON.parse(localStorage['phim1080-collections']||'[]')
collections=collections.filter((item)=>item.id!==data.id)
collections.unshift(data)
collections=collections.slice(0,28)
localStorage['phim1080-collections']=JSON.stringify(collections)
Toastify({text:"Đã thêm vào bộ sưu tập",duration:3000,gravity:"bottom",position:"center",backgroundColor:"#0a0c0f",}).showToast()})})